In [1]:
import numpy as np

In [2]:
# create an array from a list
arr = np.array([1,2,3,4,8])
print(arr)

[1 2 3 4 8]


In [5]:
#  create an with regularly spaced values
a_range = np.arange(0,10)
print(a_range)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
# create an array with evenly spaced values
a_linspace = np.linspace(0,10,5)
print(a_linspace)

[ 0.   2.5  5.   7.5 10. ]


In [9]:
random_uniform = np.random.rand(5)
print(random_uniform)

[0.24781363 0.74652484 0.39666737 0.90018246 0.65606215]


In [10]:
random_normal= np.random.randn(10)
print(random_normal)

[ 0.87137503 -0.50567386 -1.53743235  0.57028105 -0.09876952 -0.11454672
  0.38613153 -1.00084948 -1.05258169  0.17091   ]


In [13]:
arr = np.array([[1,2,3],[4,5,6]])
shape = np.shape(arr)
print(shape)
size= np.size(arr)
print(size)

(2, 3)
6


In [12]:
# dtype=np.size(arr)

In [16]:
a =np.array([1,2,3,4,5,6,7,8,])
first_element = a[0]
print(first_element)
sliced_array = a[1:4]
print(sliced_array)

1
[2 3 4]


In [17]:
#  reshaping and manipulating arrays
arr = np.array([[1,2,3],[4,5,6]])
reshaped_arr= np.reshape(arr,(3,2))
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
# filtering
a = np.array([1,5,6,6,7,8,9,4,2])
filtering_arr = a[a>2]
print(filtering_arr)

[5 6 6 7 8 9 4]
